config/routes.rb
Rails.application.routes.draw do

  root to:'pokemons#new'
  resources :pokemons do
    put :calculate, on: :collection
  end

end

app/models/pokemon.rb
require 'open-uri'
require 'net/http'
class Pokemon < ActiveRecord::Base
  attr_accessor :character, :level, :p_hp, :p_attack, :p_defend, :p_sp_attack, :p_sp_defend, :p_speed
  attr_accessor :tr_hp, :tr_attack, :tr_defend, :tr_sp_attack, :tr_sp_defend, :tr_speed
  attr_accessor :real_hp, :real_attack, :real_defend, :real_sp_attack, :real_sp_defend, :real_speed

  validates_uniqueness_of :number
  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100}
  validates :p_hp, :p_attack, :p_defend, :p_sp_attack, :p_sp_defend, :p_speed, :tr_hp, :tr_attack, :tr_defend, :tr_sp_attack, :tr_sp_defend, :tr_speed, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}

  DATA_HOST = 'https://yakkun.com/sm/zukan/'
  MAX_NO = 807
  THREAD_BUCKET = 300

  has_one_attached :icon

  # 能力値＝(種族値×2＋個体値＋努力値÷4)×レベル÷100＋レベル＋10
  # 能力値＝{(種族値×2＋個体値＋努力値÷4)×レベル÷100＋5}×性格補正
  def ability_calculate(level, character_id)

    self.level = level
    if self.valid?
      pokemon_character = PokemonCharacter.find(character_id)
      Pokemon.personal_ability.each do |ability|
        if ability == "hp"
          self.send("real_#{ability}=", (self.send(ability)*2+self.send("p_#{ability}".to_sym)+self.send("tr_#{ability}".to_sym)/4)*level/100+level+10)
        else
          self.send("real_#{ability}=", ((self.send(ability)*2+self.send("p_#{ability}".to_sym)+self.send("tr_#{ability}".to_sym)/4)*level/100+5)*pokemon_character.send(ability))
        end
      end
    end
  end

  class << self
    def personal_ability
      %W( hp attack defend sp_attack sp_defend speed)
    end

    def collection
      Pokemon.pluck(:number, :name).map{|p| {value: p[0], name: p[1]}}
    end

    def sync
      thread_count = MAX_NO/THREAD_BUCKET + (MAX_NO%THREAD_BUCKET > 0 ? 1 : 0)
      thread_count.times do |index|
        numbers = MAX_NO - (index + 1) * THREAD_BUCKET > 0 ? THREAD_BUCKET : MAX_NO - index * THREAD_BUCKET
        thread = Thread.new do
          pokemons = []
          numbers.times do |number|
            uri = URI("#{DATA_HOST}n#{number + index * THREAD_BUCKET + 1}")
            result = Net::HTTP.get(uri)
            doc = Nokogiri::HTML(result)
            pokemons << parse_from_html(doc)
          end
          Pokemon.import pokemons
        end
        thread.join
      end
    end

    def parse_from_html(doc)
      status_part = doc.xpath('//div[@class="table layout_right"]/table/tr/td[@class="left"]')
      number = doc.xpath('//div[@class="table layout_left"]/table/tr[@class="center"]/td')[2].text.to_i
      name = doc.xpath('//div[@class="table layout_left"]/table/tr/th').children.first.text
      hp = status_part[0].text[1..-1].to_i
      attack = status_part[1].text[1..-1].to_i
      defend = status_part[2].text[1..-1].to_i
      sp_attack = status_part[3].text[1..-1].to_i
      sp_defend = status_part[4].text[1..-1].to_i
      speed = status_part[5].text[1..-1].to_i

      pokemon = Pokemon.find_or_initialize_by(number: number)
      pokemon.name = name
      pokemon.hp = hp
      pokemon.attack = attack
      pokemon.defend = defend
      pokemon.sp_attack = sp_attack
      pokemon.sp_defend = sp_defend
      pokemon.speed = speed

      if pokemon.new_record?
        avatar_url = doc.xpath('//div[@class="table layout_left"]/table/tr[@class="center"]/td/img/@src').text.gsub('//', 'http://')
        # avatar = open(avatar_url)

        open("assets/images/pokemon_icons/#{number}.gif", "wb") do |file|
          file<<open(avatar_url).read
        end
      end
      pokemon
    end
  end

end

app/models/pokemon_character.rb
class PokemonCharacter < ActiveRecord::Base
  def self.characters
    {
      "さみしがり" => [1.1, 0.9, 1, 1, 1],
      "いじっぱり" => [1.1, 1, 0.9, 1, 1],
      "やんちゃ" => [1.1, 1, 1, 0.9, 1],
      "ゆうかん" => [1.1, 1, 1, 1, 0.9],
      "ずぶとい" => [0.9, 1.1, 1, 1, 1],
      "わんぱく" => [1, 1.1, 0.9, 1, 1],
      "のうてんき" => [1, 1.1, 1, 0.9, 1],
      "のんき" => [1, 1.1, 1, 1, 0.9],
      "ひかえめ" => [0.9, 1, 1.1, 1, 1],
      "おっとり" => [1, 0.9, 1.1, 1, 1],
      "うっかりや" => [1, 1, 1.1, 0.9, 1],
      "れいせい" => [1, 1, 1.1, 1, 0.9],
      "おだやか" => [0.9, 1, 1, 1.1, 1],
      "おとなしい" => [1, 0.9, 1, 1.1, 1],
      "しんちょう" => [1, 1, 0.9, 1.1, 1],
      "なまいき" => [1, 1, 1, 1.1, 0.9],
      "おくびょう" => [0.9, 1, 1, 1, 1.1],
      "せっかち" => [1, 0.9, 1, 1, 1.1],
      "ようき" => [1, 1, 0.9, 1, 1.1],
      "むじゃき" => [1, 1, 1, 0.9, 1.1],
    }
  end

  def self.create_character
    self.characters.map do |key, rate_arr|
      PokemonCharacter.create(
        name: key,
        attack: rate_arr[0],
        defend: rate_arr[1],
        sp_attack: rate_arr[2],
        sp_defend: rate_arr[3],
        speed: rate_arr[4]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:calculate]
  before_action :set_pokemon_racial_params, only: [:calculate]

  def new
    @pokemon = Pokemon.new
  end

  def calculate
    @pokemon.ability_calculate(pokemon_params[:level].to_i, params[:character_id])
    render 'new'
  end

  private

    def set_pokemon
      @pokemon = Pokemon.find_by(number: pokemon_params[:number])
    end

    def pokemon_params
      params[:pokemon]
    end

    def set_pokemon_racial_params
      [:p, :tr].each do |prefix|
        [:hp, :attack, :defend, :sp_attack, :sp_defend, :speed].each do |ability|
          full_ability_name = prefix.to_s + '_' + ability.to_s
          @pokemon.send("#{full_ability_name}=", pokemon_params[full_ability_name.to_s].to_i || 0)
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokemonCalculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/_form.html.erb
<div class="container"> 
  <h2>個体値カリキュレーター (サンムーン対応)</h2>
  <br>
  <%= form_for(@pokemon, as: :pokemon, url: calculate_pokemons_path(@pokemon), method: :put) do |f|%>
    <ul>
      <% @pokemon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <div class="form-group">
      <label>Level</label>
      <%= f.number_field :level, class: 'form-control level'%>
    </div>
    <div class="form-group">
      <label>Character</label>
      <%=select_tag 'character_id', options_for_select(PokemonCharacter.all.map{|p_c| [p_c.name, p_c.id]}), id: 'characters'%>
    </div>
    <div>
      <label>Pokemon</label>
      <select id="pokemons" onchange="setIcon(this);">
        <% Pokemon.collection.each do |pokemon|%>
          <option value="<%=pokemon[:value]%>"><%=pokemon[:name]%></option>
        <% end %>
      </select>
      <%= f.hidden_field :number, value: 1%>
    </div>
    <%= image_tag '/assets/pokemon_icons/1.gif', id: 'icon'%>
    <br>
    <div class="input-groups">
      <div name="personal_ability">
        <label>個体値</label>
        <div class="form-group">      
          <label>HP</label>
          <%= f.number_field :p_hp, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Attack</label>
          <%= f.number_field :p_attack, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Defend</label>
          <%= f.number_field :p_defend, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Sp_Attack</label>
          <%= f.number_field :p_sp_attack, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Sp_Defend</label>
          <%= f.number_field :p_sp_defend, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Speed</label>
          <%= f.number_field :p_speed, class: 'form-control'%>
        </div>
      </div>
      <div name="train_ability">
        <label>努力値</label>
        <div class="form-group">      
          <label>HP</label>
          <%= f.number_field :tr_hp, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Attack</label>
          <%= f.number_field :tr_attack, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Defend</label>
          <%= f.number_field :tr_defend, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Sp_Attack</label>
          <%= f.number_field :tr_sp_attack, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Sp_Defend</label>
          <%= f.number_field :tr_sp_defend, class: 'form-control'%>
        </div>
        <div class="form-group">
          <label>Speed</label>
          <%= f.number_field :tr_speed, class: 'form-control'%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit "Calculate"%>
    </div>
  <% end %>
    <br>
    <div class="result">
      <label>能力値</label>
      <div class="form-group">      
        <label>HP</label>
        <%= @pokemon.real_hp%>
      </div>
      <div class="form-group">
        <label>Attack</label>
        <%= @pokemon.real_attack%>
      </div>
      <div class="form-group">
        <label>Defend</label>
        <%= @pokemon.real_defend%>
      </div>
      <div class="form-group">
        <label>Sp_Attack</label>
        <%= @pokemon.real_sp_attack%>
      </div>
      <div class="form-group">
        <label>Sp_Defend</label>
        <%= @pokemon.real_sp_defend%>
      </div>
      <div class="form-group">
        <label>Speed</label>
        <%= @pokemon.real_speed%>
      </div>
    </div>
</div>
<script>
  $("#pokemons").select2();
  $("#characters").select2();
  function setIcon(pokemon) {
    $('#icon').attr('src', '/assets/pokemon_icons/'+pokemon.value+'.gif'); 
   };
</script>

app/views/pokemons/new.html.erb
<%= render 'form'%>

app/views/pokemons/show.html.erb
<%= render 'form'%>